export enum DeliveryStatus {
  PENDENTE = 'PENDENTE',
  ACEITO = 'ACEITO',
  A_CAMINHO = 'A_CAMINHO',
   NO_LOCAL = 'NO_LOCAL',
  EM_ATENDIMENTO = 'EM_ATENDIMENTO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
  UNASSIGNED = 'UNASSIGNED'
}